# top level stuff you probably don't need to touch
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5


# edit here to achieve your personal greatness
url: https://www.johnpitchko.com
theme: sustain4-theme
title: John Pitchko
author: John Pitchko
description: Personal blog and resume
avatar: john-pitchko-400x400.jpg
email: john@johnpitchko.com
github: johnpitchko # username
twitter: johnpitchko
linkedin: johnpitchko
goodreads: 76989465-john-pitchko
# stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: johnpitchko
google_analytics: UA-79849295-1


# needed for travis-ci build
exclude: [vendor]

# Collections
collections:
  media:
    output: true
  books2:
    output: true
    permalink: /:collection/:name.html
  renovations:
    output: true
    image_path: /assets/img/renovations

# Plugins
plugins:
  # - jekyll-compress-images

imageoptim:
  # Disabling svgo because it throws some error
  svgo: false
  jpegrecompress:
    allow_lossy: true
    quality: 2
    # max_quality: 80
