# top level stuff you probably don't need to touch
# rdiscount:
#   extensions: [smart]
# permalink: /:title.html
# paginate: 5


# edit here to achieve your personal greatness
url: https://www.johnpitchko.com
theme: minimal-mistakes-jekyll
title: John Pitchko
# name: John Pitchko
description: Personal blog and resume
locale: "en-CA"
logo:
masthead_title: John Pitchko
email: john@johnpitchko.com
timezone: America/Edmonton
include: ["_pages"]
# github: johnpitchko # username
# twitter: johnpitchko
# linkedin: johnpitchko
# goodreads: 76989465-john-pitchko
# stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
# google_analytics: UA-79849295-1
# google_site_verification:

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: true
      related: true
      author_profile: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      read_time: false
      comments: false
      share: true
      related: false
      author_profile: true



comments:
  provider: "disqus"
  disqus:
    shortname: "johnpitchko"

twitter:
  username: "johnpitchko"

social:
  type: Person
  name: John Pitchko
  links:
    - "https://twitter.com/johnpitchko"
    # TODO: add more

analytics:
  provider: "google"
  google:
    tracking_id: "UA-79849295-1"

author:
  name: "John Pitchko"
  avatar: "/assets/img/john-pitchko-400x400.jpg"
  bio: "Associate Dean, SAIT Polytechnic"
  location: "Calgary, AB"
  links:
    - label: "johnpitchko.com"
      icon: "fas fa-fw fa-link"
      url: "https://www.johnpitchko.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/johnpitchko/"
    - label: 'Twitter'
      icon: 'fab fa-fw fa-twitter-square'
      url: 'https://www.twitter.com/johnpitchko'

#TODO: add compress_html gem and config



# Collections
collections:
  books2:
    output: true
    permalink: /:collection/:name.html
  renovations:
    output: true
    permalink: /:collection/:name.html

# Plugins
plugins:
  # - jekyll-compress-images

imageoptim:
  # Disabling svgo because it throws some error
  svgo: false
  jpegrecompress:
    allow_lossy: true
    quality: 2
    # max_quality: 80
