---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _books2
  label: Books2
  create: all
  match: "**/*"
- type: directory
  path: _media
  label: Media
  create: all
  match: "**/*"
upload_dir: assets/uploads
public_path: assets/uploads
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  output_directory: _site
